#!/usr/bin/env bash
# displays Best School 10 times
n=1
while [ $n -le 20 ];
do
	echo $n
	case $n in

		4)
			echo "bad luck form China"
			;;

		9)
			echo "bad luck from Japan"
			;;

		17)
			echo "bad luck from Italy"
			;;
	esac
	(( n++ ))
done
