#!/usr/bin/env bash
# imitates a clock

HOUR=0
while [ "$HOUR" -lt 13 ]; do
    echo "Hour: $HOUR"
    MINUTE=1
    while [ "$MINUTE" -lt 60 ]; do
	echo "$MINUTE"
	((MINUTE++))
    done
    ((HOUR++))
done
